# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication, QMainWindow
from ui.startWindow1 import StartExpWindow1


class MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.move(0,0)
        MainWindow.setWindowFlags(Qt.FramelessWindowHint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.startExp = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startExp.sizePolicy().hasHeightForWidth())
        self.startExp.setSizePolicy(sizePolicy)
        self.startExp.setMinimumSize(QtCore.QSize(400, 500))
        self.startExp.setObjectName("startExp")
        self.horizontalLayout.addWidget(self.startExp)
        spacerItem = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.deviceSta = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deviceSta.sizePolicy().hasHeightForWidth())
        self.deviceSta.setSizePolicy(sizePolicy)
        self.deviceSta.setMinimumSize(QtCore.QSize(400, 500))
        self.deviceSta.setSizeIncrement(QtCore.QSize(500, 0))
        self.deviceSta.setObjectName("deviceSta")
        self.horizontalLayout.addWidget(self.deviceSta)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NeuroStudent采集系统"))
        self.startExp.setText(_translate("MainWindow", "开始实验"))
        # 开始实验按钮的点击事件绑定
        self.startExp.clicked.connect(lambda : self.startExperiment())
        self.deviceSta.setText(_translate("MainWindow", "设备状态"))

    def startExperiment(self):
        print("开始实验")
        # 进入开始实验流程
        # 进入实验者信息输入页面
        startWindow1 = StartExpWindow1()
        startWindow1.show()

        self.MainWindow.hide()


